language: cpp

compiler:
  - gcc
  - clang

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION ../test
  - make
  - ./utest_test
